<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /post-viewer-event
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: post-viewer-event.php	Friday 23rd of February 2024 10:42:18 AM	ayoola@ayoo.la $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1708684938 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'pc_layout_y2ccc', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1708684938 )
                            foreach( $x_1708684938 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/pc_layout_y2ccc/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Thursday 22nd of February 2024 10:37:55 PM	 $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html lang="en">

<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="theme-color" content="#000000">
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="">
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="">
    <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_y2ccc/static/js/main.781fe1a6.js"></script>
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_y2ccc/static/css/main.98658177.css">
    <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_y2ccc/js/script.js"></script>

</head>

<body data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>
    <div id="root" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
        <?php
//pc_body_2 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_body_2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
					if( empty( $_5f7fcd00f051f8bc3b70de0bd8827733 ) || ! is_object( $_5f7fcd00f051f8bc3b70de0bd8827733 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_5f7fcd00f051f8bc3b70de0bd8827733, '' );

					
//pc_body_2 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_body_2 /post-viewer-event Begins Here

//pc_body_2 /post-viewer-event Ends Here
?><?php
//oneness /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_oneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//oneness /layout/pc_layout_y2ccc/template Ends Here
?><?php
//oneness /post-viewer-event Begins Here

//oneness /post-viewer-event Ends Here
?><section data-pc-all-sections="1" class="container pc-element-with-no-space">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_middlebar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//middlebar /layout/pc_layout_y2ccc/template Ends Here
?><?php
//middlebar /post-viewer-event Begins Here

//middlebar /post-viewer-event Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_twosome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome1 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//twosome1 /post-viewer-event Begins Here

					if( empty( $_ba00c417392f313d085c334b01d34745 ) || ! is_object( $_ba00c417392f313d085c334b01d34745 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_ba00c417392f313d085c334b01d34745, '' );

					
//twosome1 /post-viewer-event Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_twosome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome2 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//twosome2 /post-viewer-event Begins Here

					if( empty( $_b2b60cf4e282e825565571169235ed74 ) || ! is_object( $_b2b60cf4e282e825565571169235ed74 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_b2b60cf4e282e825565571169235ed74, 'dark' );

					
					if( empty( $_f54fa8e8f94665b5170db9c91cc00b8a ) || ! is_object( $_f54fa8e8f94665b5170db9c91cc00b8a ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_f54fa8e8f94665b5170db9c91cc00b8a, 'well' );

					
//twosome2 /post-viewer-event Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_threesome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome1 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//threesome1 /post-viewer-event Begins Here

//threesome1 /post-viewer-event Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_threesome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome2 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//threesome2 /post-viewer-event Begins Here

//threesome2 /post-viewer-event Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_threesome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome3 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//threesome3 /post-viewer-event Begins Here

//threesome3 /post-viewer-event Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_foursome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome1 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//foursome1 /post-viewer-event Begins Here

//foursome1 /post-viewer-event Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_foursome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome2 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//foursome2 /post-viewer-event Begins Here

//foursome2 /post-viewer-event Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_foursome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome3 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//foursome3 /post-viewer-event Begins Here

//foursome3 /post-viewer-event Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_foursome4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome4 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//foursome4 /post-viewer-event Begins Here

//foursome4 /post-viewer-event Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_leftbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbar /layout/pc_layout_y2ccc/template Ends Here
?><?php
//leftbar /post-viewer-event Begins Here

//leftbar /post-viewer-event Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_leftbarright as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbarright /layout/pc_layout_y2ccc/template Ends Here
?><?php
//leftbarright /post-viewer-event Begins Here

//leftbarright /post-viewer-event Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_rightbarleft as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbarleft /layout/pc_layout_y2ccc/template Ends Here
?><?php
//rightbarleft /post-viewer-event Begins Here

//rightbarleft /post-viewer-event Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_rightbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbar /layout/pc_layout_y2ccc/template Ends Here
?><?php
//rightbar /post-viewer-event Begins Here

//rightbar /post-viewer-event Ends Here
?>
											</div>   
										</div> 
									</div> 
									</section><?php
//lastoneness /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_lastoneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//lastoneness /layout/pc_layout_y2ccc/template Ends Here
?><?php
//lastoneness /post-viewer-event Begins Here

					if( empty( $_f6c2bfae36b95c212f171e148c0f17a6 ) || ! is_object( $_f6c2bfae36b95c212f171e148c0f17a6 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_f6c2bfae36b95c212f171e148c0f17a6, '' );

					
					if( empty( $_07aeba3f690e6326ffc951b549a3e44a ) || ! is_object( $_07aeba3f690e6326ffc951b549a3e44a ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_07aeba3f690e6326ffc951b549a3e44a, '' );

					
					if( empty( $_ec25c77f96077473238bd27a0724136c ) || ! is_object( $_ec25c77f96077473238bd27a0724136c ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_ec25c77f96077473238bd27a0724136c, 'well' );

					
					if( empty( $_3ef7c7f3e1884a3e12bc40f1264ebf29 ) || ! is_object( $_3ef7c7f3e1884a3e12bc40f1264ebf29 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_3ef7c7f3e1884a3e12bc40f1264ebf29, '' );

					
//lastoneness /post-viewer-event Ends Here
?>

        <?php
//pc_body_3 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_body_3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_3 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_body_3 /post-viewer-event Begins Here

//pc_body_3 /post-viewer-event Ends Here
?>

        <?php
//pc_body_4 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_body_4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_4 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_body_4 /post-viewer-event Begins Here

//pc_body_4 /post-viewer-event Ends Here
?>

        <?php
//pc_body_5 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_body_5 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_5 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_body_5 /post-viewer-event Begins Here

//pc_body_5 /post-viewer-event Ends Here
?>

        <?php
//pc_body_6 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_body_6 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
					if( empty( $_109e65f75935ac73578bf8a3293af2ec ) || ! is_object( $_109e65f75935ac73578bf8a3293af2ec ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_109e65f75935ac73578bf8a3293af2ec, '' );

					
//pc_body_6 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_body_6 /post-viewer-event Begins Here

//pc_body_6 /post-viewer-event Ends Here
?>

        <?php
//pc_body_7 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_body_7 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_7 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_body_7 /post-viewer-event Begins Here

//pc_body_7 /post-viewer-event Ends Here
?>

        <?php
//pc_body_8 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_body_8 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_8 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_body_8 /post-viewer-event Begins Here

//pc_body_8 /post-viewer-event Ends Here
?>

        <?php
//pc_body_9 /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_body_9 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
					if( empty( $_8eda884fc70ba2424f8a205921c45b52 ) || ! is_object( $_8eda884fc70ba2424f8a205921c45b52 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_8eda884fc70ba2424f8a205921c45b52, '' );

					
//pc_body_9 /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_body_9 /post-viewer-event Begins Here

//pc_body_9 /post-viewer-event Ends Here
?>

    </div>

<?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?><?php
//pc_section_after_js /layout/pc_layout_y2ccc/template Begins Here

                foreach( $_sitePageWidget_pc_section_after_js as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_section_after_js /layout/pc_layout_y2ccc/template Ends Here
?><?php
//pc_section_after_js /post-viewer-event Begins Here

//pc_section_after_js /post-viewer-event Ends Here
?>
</body>

</html>
